### ISSUE TITLE
Update to 25APR2022 build

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#102]
Requires updates to covariance (and maybe localization) as a result of https://github.com/JCSDA-internal/mpas-jedi/pull/705.  Progress in [feature/25APR2022](https://github.com/NCAR/MPAS-Workflow/tree/feature/25APR2022).

**Comment by byoung-joo** [comment]
I re-generated the 120 km static B files. Would you try these please ? Thank you!

For https://github.com/NCAR/MPAS-Workflow/blob/feature/25APR2022/config/mpas/OIE120km/mesh.csh#L29-L33 ,
```
setenv bumpCovPrefix mpas_parametersbump_cov
setenv bumpCovDir /glade/scratch/bjung/pandac/20220425_develop/NICAS_00
setenv bumpCovStdDevFile /glade/scratch/bjung/pandac/20220425_develop/CMAT_00/mpas.stddev.2018-04-15_00.00.00.nc
setenv bumpCovVBalPrefix mpas_vbal
setenv bumpCovVBalDir /glade/scratch/bjung/pandac/20220425_develop/VBAL_00
```

I can also re-generate the 60 km static B files if needed.

**Comment by byoung-joo** [comment]
Although the 60km 3dvar is not a part of regular workflows, we can fill the following env variables for 60km mesh : 
 https://github.com/NCAR/MPAS-Workflow/blob/feature/25APR2022/config/mpas/OIE60km/mesh.csh#L29-L33 .

```
setenv bumpCovPrefix mpas_parametersbump_cov
setenv bumpCovDir /glade/scratch/bjung/pandac/20220425_develop/60km.NICAS_00
setenv bumpCovStdDevFile /glade/scratch/bjung/pandac/20220425_develop/60km.CMAT_00/mpas.stddev.2018-04-15_00.00.00.nc
setenv bumpCovVBalPrefix mpas_vbal
setenv bumpCovVBalDir /glade/scratch/bjung/pandac/20220425_develop/60km.VBAL_00
```

**Comment by jjguerrette** [comment]
Thanks @byoung-joo.  I'm updating the branch now.
