### ISSUE TITLE
Update to latest build

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#124]
List of changes needed:

- [x] GNSSRO naming, similar to https://github.com/JCSDA-internal/mpas-jedi/pull/746

- ~~[ ] Updated localization files?~~

- [x] Updated covariance files

In progress: https://github.com/NCAR/MPAS-Workflow/tree/feature/12JUL2022Build

**Comment by jjguerrette** [comment]
@byoung-joo, do you have any sense of whether updated localization or covariance files are needed if I move the workflow to a recent build?  There were a lot of `saber` PR's recently.  The previous build was `16MAY2022`.

**Comment by jjguerrette** [comment]
@liujake, do you prefer that the latest build uses @metdyn's single-precision settings?  If not, it would be good to have a single-precision GNU MPT standalone build of MPAS-A that includes all of @syha's bugfixes.

**Comment by byoung-joo** [comment]
>  @byoung-joo, do you have any sense of whether updated localization or covariance files are needed if I move the workflow to a recent build? There were a lot of saber PR's recently. The previous build was 16MAY2022.


@jjguerrette , I think it would be fine with version of `16May2022`.
When I check `saber` repository, there is no change in the result for our use-case: `common` localization with `forced_radii`.

**Comment by jjguerrette** [comment]
@syha, you may try the [feature branch](https://github.com/NCAR/MPAS-Workflow/tree/feature/12JUL2022Build) if you like.  Currently I am running the automated tests.  After I have them passing, I will submit a PR.  Note that my latest build includes both of your bug fixes for `JCSDA-Internal/MPAS-Model:release-stable`, such that you will not need to specify your own build for the bundle anymore.  However, the forecast executable (config/builds.csh) still needs to be updated to include your IAU bug fixes.

**Comment by liujake** [comment]
> @liujake, do you prefer that the latest build uses @metdyn's single-precision settings? If not, it would be good to have a single-precision GNU MPT standalone build of MPAS-A that includes all of @syha's bugfixes.

From @metdyn 's cycling tests, single-precision build works well. so I think it is good to use single-precision build within mpas-bundle. This will save some memory.

**Comment by jjguerrette** [comment]
Thanks @liujake for your input.  Agreed.

@syha, the MPAS-Workflow tests passed with the double precision build of the bundle and `feature/12JUL2022Build`, but now I am re-building the bundle in single precision.  I should have a PR to MPAS-Workflow ready this afternoon that includes all the changes.  You will no longer need to modify the bundle or forecast builds in your `feature/iau` branch.

**Comment by jjguerrette** [comment]
> When I check `saber` repository, there is no change in the result for our use-case: `common` localization with `forced_radii`.

Thank you for checking @byoung-joo!  Which reference file is it so that anybody can check it in the future?  Is there another one that would tell us if the 60km/120km static B files need updating?

**Comment by byoung-joo** [comment]
@jjguerrette , It's not very straightforward to check that.

I took a look at following files:
- fv3-jedi generates the NICAS files with `forced_radii` and `specific_univariate`. The reference results didn't change other than some formatting from recent SABER changes.
https://github.com/JCSDA-internal/fv3-jedi/blob/develop/test/testinput/bumpparameters_nicas_gfs.yaml
https://github.com/JCSDA-internal/fv3-jedi/blob/develop/test/testoutput/bumpparameters_nicas_gfs.ref

- From SABER, I have checked that the contents of `test_1-1_nicas.nc` didn't change from recent SABER changes.
https://github.com/JCSDA-internal/saber/blob/develop/test/testinput/bump_nicas_fixed_radii_profiles.yaml
https://github.com/JCSDA-internal/saber-data/blob/develop/testref/bump_nicas_fixed_radii_profiles/test_1-1_nicas.nc



- For static B, yes, we need to update these files.  And the following files can be monitored ...
https://github.com/JCSDA-internal/mpas-jedi/commits/develop/test/testoutput/parameters_bumpcov.ref
https://github.com/JCSDA-internal/saber/blob/develop/test/testinput/bump_hdiag-nicas_cor_specific_univariate.yaml
https://github.com/JCSDA-internal/saber-data/blob/develop/testref/bump_hdiag-nicas_cor_specific_univariate/test_1-1_nicas.nc
https://github.com/JCSDA-internal/saber/blob/develop/test/testinput/bump_read_vbal_cov_local.yaml
https://github.com/JCSDA-internal/saber-data/blob/develop/testref/bump_read_vbal_cov_local/test_10-1_vbal_local_000010-000001.nc
https://github.com/JCSDA-internal/saber/blob/develop/test/testinput/qg_error_covariance_training_bump_cov.yaml
https://github.com/JCSDA-internal/saber-data/blob/develop/testref/qg_error_covariance_training_bump_cov/test.log.out
https://github.com/JCSDA-internal/saber/blob/develop/test/testinput/qg_error_covariance_training_bump_vbal_update.yaml
https://github.com/JCSDA-internal/saber-data/blob/develop/testref/qg_error_covariance_training_bump_vbal_update/test.log.out

I can regenerate the 60km/120km static B files with `12JUL2022Build`!

**Comment by jjguerrette** [comment]
> I can regenerate the 60km/120km static B files with `12JUL2022Build`!

Thank you @byoung-joo!  Please post the location here when they are ready.  I will wait to merge the PR until then.

**Comment by byoung-joo** [comment]
@jjguerrette , the statistics were re-generated as following. Thank you!

    60km:
      bumpCovDir: /glade/scratch/bjung/pandac/20220712_build/60km.NICAS_00
      bumpCovStdDevFile: /glade/scratch/bjung/pandac/20220712_build/60km.CMAT_00/mpas.stddev.2018-04-15_00.00.00.nc
      bumpCovVBalDir: /glade/scratch/bjung/pandac/20220712_build/60km.VBAL_00
    120km:
      bumpCovDir: /glade/scratch/bjung/pandac/20220712_build/NICAS_00
      bumpCovStdDevFile: /glade/scratch/bjung/pandac/20220712_build/CMAT_00/mpas.stddev.2018-04-15_00.00.00.nc
      bumpCovVBalDir: /glade/scratch/bjung/pandac/20220712_build/VBAL_00

**Comment by jjguerrette** [comment]
Thanks!  I am re-running the 120km 3dvar tests with the updated settings.  Then I will push after success.
