### ISSUE TITLE
CleanBase waiting [7-27]

### ISSUE THREAD

**Issue by metdyn** [NCAR/MPAS-Workflow#131]
I initiated  3denvar-60-iter_OIE120km_WarmStart_2022-07-27_all  in midnight using the develop branch checked out on 07-27. When I check back 9 hours later, I see the job is paused at 2018041512T00 due to CleanBase waiting. 

I used double precision build for mpas-jedi from today. 

I wonder why this happens (e.g., node failure) and why cleanVariational was waiting.

I tried both 

cylc trigger 3denvar-60-iter_OIE120km_WarmStart_2022-07-27_all "\*.\*:submit-failed" 

cylc trigger 3denvar-60-iter_OIE120km_WarmStart_2022-07-27_all "*\.\*:failed" 

So far neither worked.
I will start from scratch again to see if this problem still exists. 

![Screen Shot 2022-07-27 at 9 32 29 AM](https://user-images.githubusercontent.com/36313912/181288232-560c2724-162a-4d73-8161-53c63f09a5c0.png)

**Comment by metdyn** [comment]
I see (maybe this is the cause)

VerifyObsDA/01/job.out:2022-07-27T01:24:45-06:00 WARNING - Message send failed, try 1 of 7: Cannot connect: http://128.117.211.242:43010/put_messages: HTTPConnectionPool(host='128.117.211.242', port=43010): Max retries exceeded with url: /put_messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b7dc825fc50>: Failed to establish a new connection: [Errno 113] No route to host',))
VerifyObsDA/01/job.out:2022-07-27T01:24:58-06:00 WARNING - Message send failed, try 2 of 7: Cannot connect: http://128.117.211.242:43010/put_messages: HTTPConnectionPool(host='128.117.211.242', port=43010): Max retries exceeded with url: /put_messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b7dc82392d0>: Failed to establish a new connection: [Errno 113] No route to host',))

You can check the files here:
cd   /glade/scratch/USER/br_autotest/br_2022-07-27/
flow:   MPAS-Workflow_2022-07-27_all_3denvar_OIE120km_WarmStart
output:  USER_3denvar-60-iter_OIE120km_WarmStart_2022-07-27_all
log:   /glade/scratch/USER/cylc-run

**Comment by jjguerrette** [comment]
Looks like the VerifyObsDA task is hanging.  Sometimes the cylc GUI will report that a job is "submitted" even though it has already "failed".  When this happens, it is useful to execute `qstat -u $USER`.  If the job in question does not show up, then my normal practice is to change the job status from "submitted" to "failed".  Then I manually trigger that task (`VerifyObsDA` in this case) in the GUI by right-clicking on the task, or use something like `cylc trigger 3denvar-60-iter_OIE120km_WarmStart_2022-07-27_all "*.*:failed"`.  Either one will work.

**Comment by jjguerrette** [comment]
Unfortunately I have been unable to determine a robust solution for this problem that does not require manual intervention.  Any ideas you have are welcome @metdyn.

**Comment by metdyn** [comment]
@jjguerrette, Thanks for the instruction.  Your manual GUI manipulation works very well for me!!!   (I am a new user to cylc and will think about it when more similar issues are encountered).  Now the code is proceeding from 0415T12 to 0417T00.  The cleanbase does not pose an issue.

However, I find another concern in  log/job/20180415T1200-06/VerifyObsDA/01/job.out.  I see my ~/.bash_profile is either inherited or sourced, but I donot have python env. loaded there.  Nonetheless, there is no error due to use of python. I will keep an eye on the environment. 


```
Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/glade/u/home//.bash_profile: line 14: module: command not found
/glade/u/home//.bash_profile: line 17: module: command not found

Wed Jul 27 01:24:30 MDT 2022
2022-07-27T01:24:30-06:00 INFO - started

python DiagnoseObsStatistics.py -n 36 -p /glade/scratch/USER/_3denvar-60-iter_OIE120km_WarmStart_2022-07-27_all/CyclingDA/2018041512/dbOut -o obsout -g geoval -d ydiags -app variational -nout 1


2022-07-27T01:24:45-06:00 WARNING - Message send failed, try 1 of 7: Cannot connect: http://128.117.211.242:43010/put_messages: HTTPConnectionPool(host='128.117.211.242', port=43010): Max retries exceeded with url: /put_messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b7dc825fc50>: Failed to establish a new connection: [Errno 113] No route to host',))
```

**Comment by metdyn** [comment]
Hi everyone,

I feel happy that the [7-28] auto test for 15-day 120-km 3denvar completes on Cheyenne without any error early this morning.    Thank you again @jjguerrette for the instruction!  (Closing this issue).
