### ISSUE TITLE
Fix bug in amsua_n15 PreQC

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#132]
@ibanos90, this line change introduced a bug for amsua_n15.  The PreQC filter should be like below:
```yaml
  - filter: PreQC
    maxvalue: 0
```

This is why we do not assimilate any `amsua_n15` observations in current experiments.

_Originally posted by @jjguerrette in https://github.com/NCAR/MPAS-Workflow/pull/109#discussion_r941872899_

**Comment by jjguerrette** [comment]
@ibanos90, just in case it was not clear, our group's practice for these kinds of bug fixes is to issue a PR with only the changes required to fix the bug.  Also, the branch name should start with `bugfix` instead of `feature`.  All of this helps with tracking when somebody is looking through the `git log` or PRs.  Please submit a PR with the 2 line fix today so that others can merge it to their experiment branches at their convenience.

**Comment by ibanos90** [comment]
> @ibanos90, just in case it was not clear, our group's practice for these kinds of bug fixes is to issue a PR with only the changes required to fix the bug. Also, the branch name should start with `bugfix` instead of `feature`. All of this helps with tracking when somebody is looking through the `git log` or PRs. Please submit a PR with the 2 line fix today so that others can merge it to their experiment branches at their convenience.

Thanks for clarifying that @jjguerrette. I will do as suggested.
