### ISSUE TITLE
Degradation between 16MAY and 12JUL builds

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#136]
**Describe the bug**
@ibanos90 discovered clear degradation in performance in the 120km 3denvar benchmark between these two builds.  Debugging is ongoing.

**Comment by jjguerrette** [comment]
Statistics from @metdyn's weekly cycling experiment show that the degradation first arose between the JUN09 and JUN16 builds.  Thank you @metdyn for keeping the weekly test going!  Here is one figure showing all-cell time-series comparisons of background states to GFS analyses:

![image](https://user-images.githubusercontent.com/20328709/184032637-cf162055-3ed2-48a8-bd09-219be6487045.png)

**Comment by liujake** [comment]
https://github.com/JCSDA-internal/mpas-jedi/pull/738. This ATLAS-related PR seems the only one during that week. This might be the time localization files needed to be re-generated.

**Comment by liujake** [comment]
I see @byoung-joo mentioned already this PR. Most likely new localization file will solve the degradation problem.

**Comment by liujake** [comment]
I just recall that we had a similar issue a while ago when we forgot to update localization files.

**Comment by jjguerrette** [comment]
> I just recall that we had a similar issue a while ago when we forgot to update localization files.

Yes.  There is always a judgement call to make on whether we need to update them.  It would be cumbersome to generate the files for every single SABER PR, but I could definitely do it more often.
