### ISSUE TITLE
Make changes needed for observation convention updates

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#175]
See https://github.com/orgs/JCSDA-internal/teams/jedi-models/discussions/91

Due 17JAN2022 (earlier better)

- [x] Update all pre-generated observation files (@junmeiban)
  - [x] sondes
  - [x] satwind
  - [x] sfc
  - [x] gnssro
  - [x] aircraft
  - [x] amsua
  - [x] mhs
  - [x] ahi
  - [x] abi
  - [x] iasi
- [x] Update YAMLS (@jjguerrette)
- [ ] New build (@jjguerrette)
- [x] Update https://github.com/NCAR/MPAS-Workflow/blob/develop/ObsToIODA.csh (not time sensitive since nobody is running real-time right now)

Working branch: https://github.com/NCAR/MPAS-Workflow/tree/feature/sprint-ioda-converters

**Comment by jjguerrette** [comment]
@ibanos90, just a heads up that changes are coming in observation file and yaml conventions.  This might impact your work.

**Comment by ibanos90** [comment]
> @ibanos90, just a heads up that changes are coming in observation file and yaml conventions. This might impact your work.

Thanks for letting me know @jjguerrette.

**Comment by junmeiban** [comment]
Hi @jjguerrette ,
I would like to add "ioda-upgrade-v2-to-v3.x" to  “ObsToIODA.csh”.
I have a question about how to use run “ObsToIODA”. 
I saw “scenarios/GenerateObs.yaml” and it’s a “Non-templated workflow tasks” (description from README.md).

I got the following errors when I run “./run.csh GenerateObs”.
```
./run.csh (INFO): Running the GenerateObs set of scenarios
./drive.csh (INFO): generating a new cylc suite
Mon Jan  2 11:27:26 MST 2023
./drive.csh (INFO): Initializing the MPAS-Workflow experiment directory
./drive.csh (ERROR): invalid value for firstbackground__resource
./drive.csh (ERROR): firstbackground__resource = None
firstbackground__resource: Undefined variable.
mainScriptDir: Undefined variable.
./run.csh (ERROR): error when setting up GenerateObs
```
It looks I use a wrong command to run GenerateObs. Would you please correct me? Many thanks.
Junmei

**Comment by jjguerrette** [comment]
Thank you @junmeiban for trying to update ObsToIODA.csh.  Although I have already updated it in `feature/sprint-ioda-converters` and should have told you.

I will try the GenerateObs scenario to see if I can figure out what is going on.  Although I used it previously, it might have been with a feature branch (`feature/0_pythonConfigParse`).

**Comment by junmeiban** [comment]
I saw your commits for ObsToIODA.csh. Thanks @jjguerrette

**Comment by jjguerrette** [comment]
I am still working on `ObsToIODA.csh`.  `gnssro` is not upgraded to v3.

**Comment by jjguerrette** [comment]
I'm currently working on the last step, which is creating a clean build from develop branches. A [UFO PR merge](https://github.com/JCSDA-internal/ufo/pull/2497) broke develop today.  So I'm waiting for that to be reverted.  Should be able to submit a PR to MPAS-Workflow by COB tomorrow.
