### ISSUE TITLE
Check if thinning IASI before other QC speeds up DA

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#184]
Our current working strategy for IASI assimilation is to pre-thin the observation locations in a standalone h(x) application.  There might be a simpler solution.

Another potential strategy: try moving [these lines](https://github.com/NCAR/MPAS-Workflow/blob/develop/config/jedi/ObsPlugs/variational/filtersWithBias/iasi_metop-a.yaml#L153-L154) to line 2 before all other filters.

Applies to 3 yamls:
https://github.com/NCAR/MPAS-Workflow/blob/develop/config/jedi/ObsPlugs/variational/filtersWithBias/iasi_metop-a.yaml
https://github.com/NCAR/MPAS-Workflow/blob/develop/config/jedi/ObsPlugs/variational/filtersWithBias/iasi_metop-b.yaml
https://github.com/NCAR/MPAS-Workflow/blob/develop/config/jedi/ObsPlugs/variational/filtersWithBias/iasi_metop-c.yaml

My thinking is that this will reduce the number of locations simulated by CRTM since the thinning filter will be executed before h(x).  There are also YAML options to explicitly request a filter be executed in the prior stage (before h(x)) that we could try as an alternative.  We need to look at which components of `OOPS_STATS` are most impacted by IASI.  Is it the simulateObs/setTrajectory/simulateObsAD methods?  or the UnstructuredInterpolator methods? or the ObsSpace I/O?  Pre-thinning should reduce the wall-time of simulateObs/setTrajectory/simulateObsAD, but I'm not sure about the other two contributions.

If this works, similar strategies can be applied to other radiance obs.

**Comment by liujake** [comment]
This sounds a good strategy if it works like you expected! It was one of my questions: how the order of QC filters in yaml setting will affect the results/behavior of final QCed obs. WRFDA (GSI too I believe) does thinning in the bufr file reading stage before hofx calculation. If hofx only computes on un-thinned pixels, then we have less geovals profiles in the memory, though we still keep all obs pixels, so it is a partial saving on memory if I understand this correctly.

**Comment by jjguerrette** [comment]
Yes @liujake, only a partial memory savings, if any.  As I noted, the only improvement I expect is in the CRTM operator, which can skip profiles that are flagged/filtered before h(x).
