### ISSUE TITLE
Add "keptvars.yaml" for mpas-jedi applications

### ISSUE THREAD

**Issue by byoung-joo** [NCAR/MPAS-Workflow#200]
After merging https://github.com/JCSDA-internal/mpas-jedi/pull/844, we need to add "keptvars.yaml" for mpas-jedi applications. This yaml defines the variables to be kept in memory (mpas_domain) when `geometry.deallocate non-da fields: true`.

**Comment by byoung-joo** [comment]
@jjguerrette, I don't know when the best time is to work on this because I know you are working on a major refactoring #199 and following one. I guess this work would be small one though.

**Comment by jjguerrette** [comment]
@byoung-joo, I think this work should not have any overlap with those larger refactorings.  If my memory is correct, you should only need to modify files in the `config/mpas` directory.  #199 and the follow-up do not touch that directory.  I'm going to merge #199 momentarily.

**Comment by byoung-joo** [comment]
I see, I will work on this now!
