### ISSUE TITLE
[NCAR/MPAS-Workflow] CyclingFC running with Bypass

### ISSUE THREAD

**Issue by syha** [NCAR/MPAS-Workflow#211]
**Describe the bug**
In the scenarios yaml files, 
1. Setting "CriticalPathType: Bypass" doesn't skip 6h forecasts. (But it does skip 'da'.)  
2. Even with "max active cycle points: 4" for the cheapest run on the 120-km mesh, Extended forecast jobs are kicked out of cheyenne due to exceeding the CPU limit (not right away, but after one or two cycles run).

**To Reproduce**
scenarios/3denvar_OIE120km_WarmStart.yaml defines Bypass as below.

workflow:
+CriticalPathType: Bypass    # Added for verification or extended forecasts only
=> 6h forecasts are still running under CyclingFC (instead of being skipped).

+max active cycle points: 4
=> extendedforecast jobs are kicked out of cheyenne.

**Expected behavior**
1) Bypass should skip 6h forecasts under CyclingFC.
2) Proper configuration for extended forecasts (e.g., nodes or processors) to be run for multiple cycles all at once (as they do not need cycling).

**Additional context**
Need clear guidelines for how to run extended forecasts (for mean or ensemble members) or verification (with how to specify intervals for forecasts or cycles).
I tested these in the feature/fixIAUPythonEnv branch (which is merged by now), but I would expect the same issues to happen in all the recent branches.

**Comment by jjguerrette** [comment]
Potentially the solution for https://github.com/NCAR/MPAS-Workflow/issues/143 will also fix (bug 1) in this issue.  I'm testing right now, and should be able to submit a PR today/tomorrow.

I'm a little more surprised/confused by (bug 2).  Please point me to the cylc-run directory for this suite so I can check some of the log files (if they are still there).

**Comment by syha** [comment]
For bug2, how about /glade/scratch/syha/cylc-run/syha_3denvar-60-iter_O120km/.

**Comment by jjguerrette** [comment]
I'm not sure.  It looks like your ExtendedMeanFC job succeeded...maybe.  It's hard for me to diagnose after the fact.

**Comment by jjguerrette** [comment]
Just to note, @byoung-joo reported encountering (2) today as well.  I think I need to change some of the background tasks that don't do anything (act as placeholders).  They are probably over-running the login node.

**Comment by jjguerrette** [comment]
Should be closed by #212.  Re-open if not.
