### ISSUE TITLE
Enable single-precision state files

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#22]
Currently double-precision forecast and analysis files are used across all cycles, which is quite expensive as we move toward higher resolution and more ensemble members.

It is OK to keep read double-precision first-guess and initial condition files in the first cycle as we have now, although the precision of the first cycle and the ensemble B files should be configurable in case they are only available in single-precision.

Besides the first cycle reading, make the precision of written (forecast/analysis) and read (first-guess, initial condition, and ensemble B) files configurable.  For EDA cycling, the precision of the ensemble B after the first cycle will be the same as the forecast files, but not necessarily in the first cycle.

D = double-precision
S = single-precision

**3denvar**
_Currently_:
FirstCycleBackground (**D**)
=(`variational`)=> FirstCycleAnalysis (**D**)
=(`forecast`)=> FirstCycleForecast/SecondCycleBackground(**D**)
=(`variational`)=> SecondCycleAnalysis (**D**)
...
All cycles use GEFS cold-start forecasts: EnsForCov (**D**)
OR
All cycles use previous MPAS-JEDI EDA forecasts (**D**)

_Fix in this issue_:
FirstCycleBackground (**D**)
=(`variational`)=> FirstCycleAnalysis (**D**)
=(`forecast`)=> FirstCycleForecast/SecondCycleBackground(**S**)
=(`variational`)=> SecondCycleAnalysis (**S**) ...
...
All cycles use GEFS cold-start forecasts: EnsForCov (**D**)
OR
All cycles use previous MPAS-JEDI EDA forecasts (**S**)

**eda_3denvar**
_Currently_:
FirstCycleBackgroundEnsemble (**D**)
=(`variational`)=> FirstCycleAnalysisEnsemble (**D**)
=(`forecast`)=> FirstCycleForecastEnsemble/SecondCycleBackgroundEnsemble(**D**)
=(`variational`)=> SecondCycleAnalysisEnsemble (**D**)
...
First cycle uses GEFS cold-start forecasts: EnsForCov (**D**)
OR
Second and subsequent cycles use previous MPAS-JEDI EDA forecasts (**D**)

_Fix in this issue_:
FirstCycleBackgroundEnsemble (**D**)
=(`variational`)=> FirstCycleAnalysisEnsemble (**D**)
=(`forecast`)=> FirstCycleForecastEnsemble/SecondCycleBackgroundEnsemble(**S**)
=(`variational`)=> SecondCycleAnalysisEnsemble (**S**)
...
First cycle uses GEFS cold-start forecasts: EnsForCov (**D**)
OR
Second and subsequent cycles use previous MPAS-JEDI EDA forecasts (**S**)

The precision of the input/output streams can be set in streams.atmosphere for each application using the `precision` stream key (i.e., https://www2.mmm.ucar.edu/projects/mpas/mpas_atmosphere_users_guide_7.0.pdf).

For example,
```xml
<immutable_stream name="da_state"
                  type="output"
                  precision="single"
                  clobber_mode="truncate"
                  filename_template="mpasout.$Y-$M-$D_$h.$m.$s.nc"
                  io_type="pnetcdf,cdf5"
                  output_interval="0_06:00:00" />

<stream name="background"
        type="input;output"
        precision="single"
        io_type="pnetcdf,cdf5"
        filename_template="background.nc"
        input_interval="none"
        output_interval="none"
        clobber_mode="overwrite">
        <file name="stream_list.atmosphere.background"/>
</stream>

<stream name="analysis"
        type="output"
        precision="single"
        io_type="pnetcdf,cdf5"
        filename_template="analysis.nc"
        output_interval="none"
        clobber_mode="overwrite">
        <file name="stream_list.atmosphere.analysis"/>
</stream>

<stream name="ensemble"
        type="input;output"
        precision="single"
        io_type="pnetcdf,cdf5"
        filename_template="ensemble.nc"
        input_interval="none"
        output_interval="none"
        clobber_mode="overwrite">
        <file name="stream_list.atmosphere.ensemble"/>
</stream>
```

The main challenge of this issue is to set the precision correctly for each combination of workflow application (variational, forecast, hofx, and rtpp), stream name (da_state, background, analysis, ensemble, control), and cycle (generally, first or after the first).

**Comment by jamiebresch** [comment]
My suggestion is to NOT link `an` output file to `bg` file and set clobber_mode="replace_files", then setting precision="single" in all stream should be able to still read double-precision input and have single-precision output.

**Comment by jjguerrette** [comment]
> My suggestion is to NOT link `an` output file to `bg` file and set clobber_mode="replace_files", then setting precision="single" in all stream should be able to still read double-precision input and have single-precision output.

That is interesting.  I did not know that one could still read double-precision when precision="single".  Thank you for that very useful piece of info.  For my own record, I'm going to make the solution a little more verbose, but basically just reiterating what @jamiebresch is suggesting in the following.

Previously the `bg` file was different from the forecast file, because `cldfrac` needed to be appended before `mpasjedi_variational`.  Now we include `cldfrac` in the forecast file via the `da_state` stream.  As long as the first cycle backgrounds (including EDA members) also include `cldfrac`, we can have the `bg` file link to the forecast output (`mpasout`) and copy (instead of link) the `bg` file to the `an` file before `mpasjedi_variational`.  The copying of `bg` to `an` is consistent with our current approach to ensure we have a full IC file for the following forecast without writing all of the fields required by the forecast from the DA application.  We only write the fields associated with the `analysis` stream as described in https://github.com/JCSDA-internal/mpas-jedi/pull/647.

One edge case that may still need a unique precision solution is the reading of `SST` and `XICE` variables.  Currently we either overwrite the `SST` and `XICE` values already in the forecast output files or append to those files via ncks.  Ideally we would read `SST` and `XICE` via the independent `surface` stream instead of the `input` stream during the `forecast` task.  We might also need to use the `surface` stream during the `variational` task in order to be consistent.

**Comment by jjguerrette** [comment]
Note: we still need to use clobber_mode="overwrite" if we only want to write the analysis fields (cheaper) instead of all of the records (more expensive) that will be needed in the next IC file.

[MPAS-A user guide](https://www2.mmm.ucar.edu/projects/mpas/mpas_atmosphere_users_guide_7.0.pdf), excerpt from section 5.2

clobber mode — Specifies how a stream should handle attempts to write to a file that already exists.
Possible values for the mode include:
- "overwrite" — The stream is allowed to overwrite records in existing files and to append new
records to existing files; records not explicitly written to are left untouched.
- "truncate" or "replace files" — The stream is allowed to overwrite existing files, which are
first truncated to remove any existing records; this is equivalent to replacing any existing files
with newly created files of the same name.
- "append" — The stream is only allowed to append new records to existing files; existing records
may not be overwritten.
- "never modify" — The stream is not allowed to modify existing files in any way.
