### ISSUE TITLE
[Issue Title]Missing "x1.${Mesh}.sfc_update.nc" file for extended forecast

### ISSUE THREAD

**Issue by junmeiban** [NCAR/MPAS-Workflow#222]
**Describe the bug**
"x1.${Mesh}.sfc_update.nc" file link is missed for extended forecast. So in this way "sst" and "xice" will not be updated. 
This file link existed in 6-h cycling forecast but missed in extended forecast.

**To Reproduce**
Run extended forecast

**Expected behavior**
Include "x1.${Mesh}.sfc_update.nc" file link

**Comment by liujake** [comment]
@junmeiban Can you fix this bug when you get a chance?
