### ISSUE TITLE
use intel+mpt compiled MPAS model code(outside bundle) for forecasts

### ISSUE THREAD

**Issue by junmeiban** [NCAR/MPAS-Workflow#226]
For 6h cycling forecasts and long range forecasts: use intel+mpt compiled MPAS model code.
@liujake will compile the code. @junmeiban will update the exe path in the workflow.

**Comment by liujake** [comment]
See https://github.com/NCAR/MPAS-Workflow/pull/217

**Comment by junmeiban** [comment]
This issue can be closed, as the PR https://github.com/NCAR/MPAS-Workflow/pull/230 already merged. In the future, mpas-bundle build directory will be updated and pointed to @liujake 's pandac_common.
