### ISSUE TITLE
Cylc config files should be converted to 8.0 format.

### ISSUE THREAD

**Issue by jim-p-w** [NCAR/MPAS-Workflow#267]
The cycle version being used on derecho is 8.x. The version on cheyenne was 7.x.
The file format has changed between 7.x and 8.x, so our config files must be changed to be cylc 8.x compliant.

**Comment by mos3r3n** [comment]
I think we are ready to remove Cheyenne-related features since Cheyenne has gone away.

**Comment by jim-p-w** [comment]
> I think we are ready to remove Cheyenne-related features since Cheyenne has gone away.

I am inclined to leave in the code which checks for the host, as a placeholder for the next time we get a new HPC, or the next time we change cylc versions.
As things are now, you can search the code for 'derecho' to find the system dependent things which may need to change.

**Comment by liujake** [comment]
I think it is fine to keep Cheyenne-related part for now if not affecting derecho's setting. We need to make sure we configure node/cores/memory in an optimal way for derecho. And I also think there is no need (or at least not a priority) to make code/setting generic to handle two machines's setting. Making it work on derecho properly a priority.
