### ISSUE TITLE
Library of initial states, ensemble covariance files, observation files

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#28]
Create "library" of first cycle first-guess state, `EnsForCov`, GFS analysis (for verification), and observation files easily accessible by `config/mpas/O*IE*.csh` scripts.  Each file creator uses a different naming convention, which is OK.  The point is to create a standard environment variable naming convention that can access heterogeneously-stored files that were generated external to the workflow.  All first-guess states need to be produced with the `da_state` stream (colloquially, we call those `mpasout` format).  `EnsForCov` files need only have the fields in `config/mpas/variational/stream_list.atmosphere.ensemble`: `theta`, `pressure_base`, `pressure_p`, `surface_pressure`, `uReconstructZonal`, `uReconstructMeridional`, `qv`, `qc`, `qi`, `qs`, `qr`, `qg` (those last six comprise `scalars`).

### GFS analyses
  - [ ] 120-km
    - [x] 2018041500 valid time: `/glade/p/mmm/parc/liuz/pandac_common/120km_GFSANA`
    - [x] 2020072400 valid time `/glade/p/mmm/parc/jban/pandac_common/120km_GFSANA`
  - [ ] 60-km
    - [x] 2018041500 valid time: single-precision `/glade/scratch/jban/pandac/case2018_60km_GFSANA`
    - [x] 2020072400 valid time: single-precision `/glade/scratch/jban/pandac/case2020_60km_GFSANA `
  - [ ] 30-km
    - [x] 2018041500 valid time: `/glade/p/mmm/parc/liuz/pandac_common/30km_GFSANA`
    - [x] 2020072400 valid time: `/glade/p/mmm/parc/liuz/pandac_common/30km_GFSANA_2020`
### First-guess states
- [ ] deterministic (single-state 6-hr FC from GFS)
  - [ ] 120-km
    - [x] 2018041500 valid time
      - [x] restart: `/glade/p/mmm/parc/liuz/pandac_common/120km_1stCycle_background/2018041418` 
      - [x] da_state: `/glade/p/mmm/parc/liuz/pandac_common/120km_1stCycle_background_mpasout/2018041418`
    - [x] 2020072400 valid time
      - [x] restart: `/glade/p/mmm/parc/jban/pandac/120km_2020_1stCycle_background_res/2020072318`
      - [x] da_state: `/glade/p/mmm/parc/jban/pandac/120km_2020_1stCycle_background/2020072318`
  - [ ] 60-km
    - [x] 2018041500 valid time: single-precision
      - [x]  da_state: /glade/p/mmm/parc/jban/pandac/60km_2018_1stCycle_background/2018041418/
    - [x] 2020072400 valid time: single-precision
      - [x] da_state: `/glade/p/mmm/parc/jban/pandac/60km_2020_1stCycle_background_s/2020072318` 
  - [x] 30-km
    - [x] 2018041500 valid time
      - [x] restart: `/glade/p/mmm/parc/liuz/pandac_common/30km_1stCycle_background/2018041418/`
      - [x] da_state: `/glade/p/mmm/parc/liuz/pandac_common/30km_1stCycle_background_2streams/2018041418`
    - [x] 2020072400 valid time
      - [x] da_state single-precision: `/glade/p/mmm/parc/liuz/pandac_common/30km_2020_1stCycle_background_single/2020072318`
      - [x] da_state double-precision: `/glade/p/mmm/parc/liuz/pandac_common/30km_2020_1stCycle_background/2020072318`
  - [ ] 15-km?
    - [ ] 2018041500 valid time
    - [ ] 2020072300 valid time
- [ ] stochastic (80-member 6,12,18,24-hr FC from 20-member GEFS)
  - [x] 120-km
    - [x] 2018041500 valid time: `/glade/p/mmm/parc/guerrett/pandac/fixed_input/120km/120kmEnsFCFirstCycle`
    - [x] 2020072400 valid time: `/glade/p/mmm/parc/guerrett/pandac/fixed_input/120km/120kmEnsFCFirstCycle`
  - [ ] 60-km
    - [x] 2018041500 valid time: `/glade/p/mmm/parc/guerrett/pandac/fixed_input/60km/60kmEnsFCFirstCycle`
    - [ ] 2020072400 valid time
      - [x] 20-members: `/glade/p/mmm/parc/liuz/pandac_common/60km_GEFS_init_2020/2020072318`
      - [ ] 80-members

### EnsForCov (20-member 6-hr forecasts from GEFS analyses)
  - [ ] 120-km
    - [x] `2018041500` to `2018051418` every-6-hours valid times: `/glade/p/mmm/parc/liuz/pandac_common/120km_EnsFC`
    - [x] `2020072400` to `2020082400` every-6-hours valid times:
      - [x] `/glade/scratch/jban/pandac/EnsFC_120km` 
      - [x] or campaign storage` /glade/campaign/mmm/parc/jban/pandac/EnsFC_120km/`
  - [x] 60-km
    - [x] `2018041500` to `2018051418` every-6-hours valid times: `/glade/p/mmm/parc/liuz/pandac_common/60km_EnsFC_2020`
    - [x] `2020072400` to `2020082400` every-6-hours valid times: `/glade/p/mmm/parc/liuz/pandac_common/60km_EnsFC_2020`

### Observations
- 2018
  - NCDIAG
    - conventional: /glade/p/mmm/parc/liuz/pandac_common/ioda_obs_v2/2018/conv_obs
      - [x] satwind
      - [x] sfc
      - [x] aircraft
      - [x] sondes
      - [x] gnssro
    - GSI bias correction applied: /glade/p/mmm/parc/liuz/pandac_common/ioda_obs_v2/2018/bias_corr
      - [x] amsua (n15, n18, n19, metop-a, metop-b, aqua)
    - no bias correction applied: /glade/p/mmm/parc/liuz/pandac_common/ioda_obs_v2/2018/no_bias 
      - [x] mhs (n18, n19, metop-a, metop-b)
      - [x] amsua (n15, n18, n19, metop-a, metop-b, aqua)
  - Raw: /glade/p/mmm/parc/liuz/pandac_common/ioda_obs_v2/2018/raw_obs
    - [x] satwind
    - [x] sfc
    - [x] aircraft
    - [x] sondes
    - [x] gnssro
    - [x] amsua (n15, n18, n19, metop-a, metop-b, aqua)
  - ABI: /glade/work/guerrett/pandac/obs/ABIASR/ioda-v2
    - [x] 15x15 super-ob grid
    - [x] 59x59 super-ob grid
  - AHI: /glade/work/guerrett/pandac/obs/AHIASR/ioda-v2
    - [x] 15x15 super-ob grid
    - [x] 101x101 super-ob grid
- 2020
  - Raw: /glade/p/mmm/parc/liuz/pandac_common/ioda_obs_v2/2020
    - [x] satwind
    - [x] sfc
    - [x] aircraft
    - [x] sondes
    - [x] gnssro
    - [x] amsua (n15, n18, n19, metop-a, metop-b, aqua)

**Comment by junmeiban** [comment]
Hi @jjguerrette , for case 2020, I think the first cycle should be 2020072400, right? Can I add the followings directly on your issue description?

- deterministic, 120km, 2020072400 valid time
/glade/p/mmm/parc/liuz/pandac_common/2020_fixed_input/120km_1stCycle_background/2020072318/
- deterministic, 60km, 2020072400 valid time
/glade/p/mmm/parc/jban/pandac_common/60km_1stCycle_background

-  EnsForCov, 120-km, 2020 case: /glade/campaign/mmm/parc/jban/pandac/EnsFC_120km/

- stochastic, 60-km, 2018041500 valid time, 20-members: /glade/campaign/mmm/parc/jban/pandac/case2018_60km_GEFS_INIT/output/

**Comment by jjguerrette** [comment]
> for case 2020, I think the first cycle should be 2020072400, right? Can I add the followings directly on your issue description?

@junmeiban yes, thank you for the correction.  Please add those entries in the correct locations of the table or add more entries if some are missing.

**Comment by jjguerrette** [comment]
For now the directories in the issue description are linked to subdirectories within
`/glade/p/mmm/parc/guerrett/pandac/fixed_input/120km`
`/glade/p/mmm/parc/guerrett/pandac/fixed_input/60km`
`/glade/p/mmm/parc/guerrett/pandac/fixed_input/30km`

Each of those mesh-specific directories contains these subdirectories:
`SingleFCFirstCycle` - 6-hr forecast from GFS analysis valid at the first cycle date
`EnsFCFirstCycle` - 80-member 6-, 12-, 18-, and 24-hr forecasts from GEFS analyses valid at the first cycle date
`EnsForCov` - truncated 6-hr ensemble forecasts from GEFS analyses
`GFSAna` - used for model-space verification on the outer-loop mesh and for SST,XICE update (latter is only available for 120km and 30km)
`bumploc` - bump localization files for various processor counts

Also see `/glade/p/mmm/parc/guerrett/pandac/fixed_input/GEFS/surface/000hr` for ensemble-member-specific surface update files (SST+XICE).  Currently only covers the 2018 period.  I need full-period GEFS ungrib files for 2020 in order to generate the surface update files, but it's not a high priority.

All of the above is enabled in real cycling experiments within #38.

An follow-on to this effort would be to add automatic generation of all of those kinds of files to MPAS-Workflow.  That would be a much larger undertaking.

**Comment by jjguerrette** [comment]
Done for now.  Can re-open if new data sources are needed.
