### ISSUE TITLE
Forecast step in 3D DA should NOT output HOURLY forecast files

### ISSUE THREAD

**Issue by liujake** [NCAR/MPAS-Workflow#280]
Hi @RGNystrom 
When I tried 120km 3DEnVar Cycling, I noticed the forecast step runs 9-hour forecast with hourly output. I believe this is the cause of a failure I encountered. See the PR I just opened. I guess slow disk I/O (this happens often recently) made the forecast job failed. I guess this is due to your modification for 4DEnVar. Can you fix this? e.g., we should only do 9-hour forecast with hourly output for 4DEnVar mode,  but not for any 3D DA mode. I am not sure where to modify to make this configurable during the run-time.

Another thing is that the forecast output is from hour-1 instead of hour-0. We might want to go back to output from hour-0, as hour-0 forecast includes re-diagnosed pressure field, which might not be exactly the same as the analysis file, and could be useful for diagnostic purposes.

**Comment by RGNystrom** [comment]
@liujake, I can certainly take a look at this. I do not not have issues currently running 3DEnVar, but I agree that the 9 h forecast with hourly output is not needed for 3DEnVar, so an update is a good idea.

I do not understand your second point about the forecast output being from hour-1 instead of hour-0. Can you clarify?

**Comment by byoung-joo** [comment]
> I do not understand your second point about the forecast output being from hour-1 instead of hour-0. Can you clarify?

I think Jake might want to keep the 0 hour forecast (in mpasout form; `hour-1` seems to be a typo --> `hour+1`). Currently, we remove the zero-hour forecast file.

https://github.com/NCAR/MPAS-Workflow/blob/develop/bin/Forecast.csh#L30-L31
https://github.com/NCAR/MPAS-Workflow/blob/develop/initialize/applications/Forecast.py#L137

**Comment by RGNystrom** [comment]
@byoung-joo got it that makes sense, thanks for the clarification.

**Comment by liujake** [comment]
Take a look at /glade/derecho/scratch/liuz/pandac/liuz_3denvar-60-iter_O120km_VarBC/CyclingFC/2018041500/. We had mpasout.2018-04-15_00.00.00.nc in old runs.
