### ISSUE TITLE
The time window format for yaml files has changed in the develop branch of mpas-jedi

### ISSUE THREAD

**Issue by jim-p-w** [NCAR/MPAS-Workflow#284]
The yaml files which specify `window begin` and `window length` must be changed.
The new format (in the develop branch of mpas-jedi) is
```
time window:
  begin:
  length:
```

[See discussion 75 in JCSDA-internal](https://github.com/orgs/JCSDA-internal/discussions/75) and
[PR 932 in mpas-jedi](https://github.com/JCSDA-internal/mpas-jedi/pull/932)

**Comment by liujake** [comment]
Yes. But we need to first make current develop branch work properly with 2.1 code, then cut off a branch named with v2.1 for our experimentation. Then we can continue to fix this to make it with the develop code.

**Comment by jim-p-w** [comment]
> Yes. But we need to first make current develop branch work properly with 2.1 code, then cut off a branch named with v2.1 for our experimentation. Then we can continue to fix this to make it with the develop code.

@liujake You mean make the develop branch of MPAS-Workflow work with the release/2.1.0 branch of mpas-bundle?

**Comment by liujake** [comment]
Yes. We still have at least 2 remaining issue #278 and #280 to be resolved.

**Comment by liujake** [comment]
This is resolved.
