### ISSUE TITLE
ncar_pylib cannot be loaded in observation space verification

### ISSUE THREAD

**Issue by junmeiban** [NCAR/MPAS-Workflow#3]
In this workflow both of observation space and model space need ncar_pylib. When I run model space verification, the ncar_pylib can be loaded. But for observation space verification,  ncar_pylib cannot be loaded correctly.  
Both of the scripts verifymodel.csh and verifyobs.csh have similar code structure, and it works for @jjguerrette. So not sure what caused the problem.

**Comment by jjguerrette** [comment]
Closed by #4
