### ISSUE TITLE
Add IASI observations to MPAS-Workflow

### ISSUE THREAD

**Issue by ibanos90** [NCAR/MPAS-Workflow#57]
Enhance the benchmark observations in current MPAS-Workflow to assimilate clear-sky IASI observations. Will start with Emily Liu’s IASI QC from GDAS yamls:
https://github.com/JCSDA-internal/ufo/blob/develop/ewok/jedi-gdas/iasi_metop-a.yaml
https://github.com/JCSDA-internal/ufo/blob/develop/ewok/jedi-gdas/iasi_metop-b.yaml

**Comment by jjguerrette** [comment]
As discussed today, this might need to be divided into two issues (and two PRs).  One issue for the initial functionality, which consists of a single or multiple cycles running successfully.  A second (optional) PR for performance tuning as a result of verification and also job request settings required to use this large data set.  Incorporation into the benchmark observations may depend on the computational cost.
