### ISSUE TITLE
Observation configuration cleanup

### ISSUE THREAD

**Issue by ibanos90** [NCAR/MPAS-Workflow#93]
This is a list of tasks that are needed in order to clean the workflow and make it more efficient:

- [x] move `IODAPrefix` out in observations.yaml
- [x] create a list of observations instead of `benchmarkobservations` in variational.yaml
- [ ] make the satellite channel selection in the yaml files much easier to read and modify

**Comment by jjguerrette** [comment]
Completed except for the third one.  Closing.  Open new relevant issues later.
